# Generated by Django 4.1.3 on 2022-12-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('captainid', models.AutoField(db_column='CaptainID', primary_key=True, serialize=False)),
                ('noofmatches', models.IntegerField(blank=True, db_column='NoOfMatches', null=True)),
                ('noofwins', models.IntegerField(blank=True, db_column='NoOfWins', null=True)),
                ('teamid', models.IntegerField(blank=True, db_column='teamID', null=True)),
            ],
            options={
                'db_table': 'captain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('matchid', models.AutoField(db_column='MatchID', primary_key=True, serialize=False)),
                ('teama_id', models.IntegerField(blank=True, db_column='teamA_ID', null=True)),
                ('teamb_id', models.IntegerField(blank=True, db_column='teamb_ID', null=True)),
                ('status', models.CharField(db_column='Status', max_length=1)),
                ('result', models.CharField(blank=True, max_length=1, null=True)),
                ('location', models.CharField(db_column='Location', max_length=20)),
                ('mdate', models.DateField(db_column='Mdate')),
            ],
            options={
                'db_table': 'matches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('teamid', models.IntegerField(db_column='TeamID', primary_key=True, serialize=False)),
                ('matchid', models.IntegerField(db_column='MatchID')),
            ],
            options={
                'db_table': 'plays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teammanagement',
            fields=[
                ('managerid', models.AutoField(db_column='ManagerID', primary_key=True, serialize=False)),
                ('teamid', models.IntegerField(blank=True, db_column='teamID', null=True)),
                ('managername', models.CharField(db_column='ManagerName', max_length=30)),
                ('battingcoach', models.CharField(db_column='BattingCoach', max_length=30)),
                ('bowlingcoach', models.CharField(db_column='BowlingCoach', max_length=30)),
            ],
            options={
                'db_table': 'teammanagement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Umpiredby',
            fields=[
                ('matchid', models.IntegerField(db_column='MatchID', primary_key=True, serialize=False)),
                ('umpireid', models.IntegerField(db_column='UmpireID')),
            ],
            options={
                'db_table': 'umpiredby',
                'managed': False,
            },
        ),
    ]
